show_copyright: false

links:
    email: me@ferugi.com
    socialmedia:
        Facebook: http://facebook.com/ferugi
        LinkedIn: https://www.linkedin.com/in/ferugi
        GitHub: https://github.com/ferugi
        #twitch: https://www.twitch.tv/furiosustv

seo:
    facebook:
        app_id: 929230953797958
    twitter:
        username: "ferugielheri"

comments:
    using: facebook     #   "facebook" or "disqus"
    facebook:
        count: 5
        width: 100%
        colorscheme: light